{% set name = "lima-vm" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lima-vm/lima/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 90485789d02071106864a3003b62975bc213dcedbcc96e53c07adc4c2a91c38d

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses
    - make
    - sed  # [unix]

test:
  commands:
    - limactl --help

about:
  home: https://github.com/lima-vm/{{ name }}
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Linux virtual machines
  dev_url: https://github.com/lima-vm/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
