{% set name = "lima-vm" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lima-vm/lima/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 49dd844715f99e86a80e13e1f37ab55e11a775aa68c099bce4f4cbf5666260c4

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses
    - make
    - sed  # [unix]

test:
  commands:
    - limactl --help

about:
  home: https://github.com/lima-vm/{{ name }}
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Linux virtual machines
  dev_url: https://github.com/lima-vm/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
