context:
  version: "1.1.0"

package:
  name: lima-vm
  version: ${{ version }}

source:
  url: https://github.com/lima-vm/lima/archive/v${{ version }}.tar.gz
  sha256: 0c5e601c3788eaaa9f45bdf00d69e23b5720dd2f35e1be36ad21c032fdabf738

build:
  number: 0
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }}
    - go-licenses
    - make
    - if: unix
      then: sed
    - if: win
      then: posix

tests:
  - script:
      - limactl --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Linux virtual machines
  homepage: https://github.com/lima-vm/lima-vm
  repository: https://github.com/lima-vm/lima-vm

extra:
  recipe-maintainers:
    - danielnachun
