context:
  version: "2.0.3"

package:
  name: lima-vm
  version: ${{ version }}

source:
  url: https://github.com/lima-vm/lima/archive/v${{ version }}.tar.gz
  sha256: 55625e642de492827e6cf7740c095822ef8193458211e286f17a3c11ebf50a93

build:
  number: 1
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }}
    - go-licenses
    - make
    - if: unix
      then: sed
      else:
        - m2-gawk
        - m2-make

tests:
  - script:
      - limactl --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Linux virtual machines
  homepage: https://lima-vm.io/
  repository: https://github.com/lima-vm/lima

extra:
  recipe-maintainers:
    - danielnachun
